export const demoUserPassword = "vibe1234";

const assetUrl = (path) => `${import.meta.env.BASE_URL}${path}`;

export const tracks = [
  {
    id: 1,
    title: "Afterglow Loop",
    artist: "Mira Vale",
    album: "City Lights EP",
    genre: "Synth Pop",
    mood: "glowing",
    coverUrl: assetUrl("assets/covers/afterglow-loop.png"),
  },
  {
    id: 2,
    title: "Blue Hour Signal",
    artist: "North Arcade",
    album: "Late Platform",
    genre: "Indie Pop",
    mood: "restless",
    coverUrl: assetUrl("assets/covers/blue-hour-signal.png"),
  },
  {
    id: 3,
    title: "Velvet Static",
    artist: "Sena Grey",
    album: "Soft Voltage",
    genre: "Alt R&B",
    mood: "magnetic",
    coverUrl: assetUrl("assets/covers/velvet-static.png"),
  },
  {
    id: 4,
    title: "Glass Coast",
    artist: "The Frameshift",
    album: "Borrowed Weather",
    genre: "Indie Rock",
    mood: "open-road",
    coverUrl: assetUrl("assets/covers/glass-coast.png"),
  },
  {
    id: 5,
    title: "Low Orbit",
    artist: "Iris Mode",
    album: "Night Maps",
    genre: "Electronic",
    mood: "focused",
    coverUrl: assetUrl("assets/covers/low-orbit.png"),
  },
  {
    id: 6,
    title: "Sunday Frequency",
    artist: "June Market",
    album: "Small Rooms",
    genre: "Lo-Fi",
    mood: "warm",
    coverUrl: assetUrl("assets/covers/sunday-frequency.png"),
  },
];

export const users = [
  {
    id: 1,
    username: "luna",
    displayName: "Luna Vale",
    avatarKey: "vinyl",
    bio: "Collects midnight synth lines and soft chorus hooks.",
    favoriteGenres: ["Synth Pop", "Dream Pop", "Electronic"],
  },
  {
    id: 2,
    username: "mika",
    displayName: "Mika Sol",
    avatarKey: "pulse",
    bio: "Always chasing warm basslines and festival-sized feelings.",
    favoriteGenres: ["Alt R&B", "House", "Neo Soul"],
  },
  {
    id: 3,
    username: "nova",
    displayName: "Nova Hart",
    avatarKey: "spark",
    bio: "Makes playlists for rainy windows and long train rides.",
    favoriteGenres: ["Indie Pop", "Bedroom Pop", "Lo-Fi"],
  },
  {
    id: 4,
    username: "kai",
    displayName: "Kai Rivers",
    avatarKey: "wave",
    bio: "A guitar riff loyalist with a weakness for big bridges.",
    favoriteGenres: ["Indie Rock", "Post-Punk", "Shoegaze"],
  },
  {
    id: 5,
    username: "iris",
    displayName: "Iris Lane",
    avatarKey: "aura",
    bio: "Searches for songs that feel cinematic before sunrise.",
    favoriteGenres: ["Ambient Pop", "Trip-Hop", "Electronic"],
  },
];

export const follows = [
  [1, 2],
  [1, 3],
  [2, 3],
  [2, 4],
  [3, 4],
  [3, 5],
  [4, 1],
  [5, 1],
  [5, 2],
];

export const seedPosts = [
  {
    id: 1,
    user: users[0],
    track: tracks[0],
    mood: "Late-night",
    caption: "This one feels like walking home while the whole city is humming.",
    createdAt: "2026-05-03 20:10:00",
    likeCount: 3,
    likedByMe: false,
  },
  {
    id: 2,
    user: users[1],
    track: tracks[2],
    mood: "Magnetic",
    caption: "Bassline of the week. No contest.",
    createdAt: "2026-05-03 19:40:00",
    likeCount: 4,
    likedByMe: true,
  },
  {
    id: 3,
    user: users[2],
    track: tracks[1],
    mood: "Restless",
    caption: "For anyone turning a bus ride into a music video.",
    createdAt: "2026-05-03 18:25:00",
    likeCount: 2,
    likedByMe: false,
  },
  {
    id: 4,
    user: users[3],
    track: tracks[3],
    mood: "Open-road",
    caption: "The chorus opens the windows by itself.",
    createdAt: "2026-05-03 17:55:00",
    likeCount: 1,
    likedByMe: false,
  },
  {
    id: 5,
    user: users[4],
    track: tracks[4],
    mood: "Focus",
    caption: "Keeping this on loop while I build the next playlist.",
    createdAt: "2026-05-03 16:30:00",
    likeCount: 1,
    likedByMe: false,
  },
];
